# Generated by Django 4.2 on 2024-11-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
